apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: my-pattern-sample
  namespace: openshift-operators
spec:
  gitSpec:
    pollInterval: 180
    multiSourceSupport: false
    targetRepo: https://github.com/machacekondra/medical-diagnosis
    targetRevision: main
  multiSourceConfig:
    clusterGroupChartGitRevision: main
    clusterGroupChartVersion: 0.0.*
    enabled: false
    helmRepoUrl: 'https://charts.validatedpatterns.io/'
  clusterGroupName: hub
