apiVersion: v1
data:
  accountID: "{{ .Values.accountID }}"
  region: "{{ .Values.region }}"
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    clustertemplates.openshift.io/cluster: "{{ .Values.clusterName }}"

